
export interface SlideProps {
  isActive: boolean;
}

export enum SlideType {
  INTRO,
  MARKET_SIZE,
  MARKET_STATUS,
  TARGET_MARKET,
  MARKET_TRENDS,
  COMPETITION,
  SWOT_ANALYSIS,
  STRENGTHS,
  STRATEGY,
  STRATEGY_DETAIL,
  AUTOMATION_ANALYSIS,
  IMPLEMENTATION_STRATEGY,
  DEV_ROADMAP,
  MVP_ARCHITECTURE,
  MVP_UI_WIREFRAME,
  MVP_DATA_UPLOAD,
  MVP_ANALYSIS_RESULT,
  MVP_REPORT_GENERATION,
  PROPOSAL_SUMMARY,
  BUSINESS_ITEMS,
  VALUE_PROP,
  OUTCOMES
}
